### ISSUE TITLE
[24.2] Cannot invoke "java.lang.Double.doubleValue()" because "this.splitterPosition" is null 

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/CommonsDemo#41]
Dragging the splitter causes the following error:

Cannot invoke "java.lang.Double.doubleValue()" because "this.splitterPosition" is null
![image](https://github.com/FlowingCode/AddonsDemo/assets/11554739/953ec67d-ddad-48a0-9b0a-f97af488f3a1)

```
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because "this.splitterPosition" is null
	at com.vaadin.flow.component.splitlayout.SplitLayout.calcNewSplitterPosition(SplitLayout.java:389)
	at com.vaadin.flow.component.splitlayout.SplitLayout.lambda$new$9b1b5227$2(SplitLayout.java:74)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:233)
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:475)
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:292)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:447)
	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:74)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:459)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$2(ServerRpcHandler.java:440)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:440)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:323)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:114)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1529)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398)
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106)
```

**Comment by javier-godoy** [comment]
Fix released with Vaadin 24.2.0.alpha3
